version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - padma-net

  padma-wa:
    build: ./ # this will rebuild from Dockerfile in ./
    # image: padma-wa:latest # this will pull the existing image
    environment:
      - PORT=8300
      - REDIS_URL=redis://redis:6379
    ports:
      - "8300:8300"
    depends_on:
      - redis
    networks:
      - padma-net
networks:
  padma-net: