services:
  padma-wa:
    build: ./ # this will rebuild from Dockerfile in ./
    # image: padma-wa:latest # this will pull the existing image
    environment:
      - API_KEY=${apikey} # loads from .env
      - PORT=8300
      - DEVICE_NAME=PADMA LOCAL
    ports:
      - "8300:8300"
    networks:
      - padma-net
networks:
  padma-net: